### ISSUE TITLE
The deployment, as written, depends on an installed keylime instance where the deployer runs

### ISSUE THREAD

**Issue by galmasi** [keylime/attestation-operator#10]
That is clearly suboptimal, although it is not an impossible requirement. @maugustosilva commented that the generation of TLS secrets requires keylime, and no one of sane mind will want to reproduce that code outside keylime just to decouple the dependency. 

At least two thoughts arose during the discussion -- (a) the secret generation is trivial boilerplate operations with `openssl` and could probably be implemented with 3 lines of bash. (b) we could use a dockerized kubernetes instance to run, either as a job with a service account, or as an init container, to generate the secret. Either way, the generation of the secret would be done as part of the deployment rather than offline in the deployer script.

**Comment by maugustosilva** [comment]
fixed by PR #8
