### ISSUE TITLE
Determine which SQL database `helm` chart could be used as a dependency for keylime

### ISSUE THREAD

**Issue by maugustosilva** [keylime/attestation-operator#5]
In scale-out deployment, the idea is to simply deploy an already existing n-way replicated SQL database which will then be used by both `Registrars` and `Verifiers`. Any input on this is greatly appreciated.

**Comment by mpeters** [comment]
Ideally we would just let the user decide, because lots of people will already have some DB deployed and may not want yet-another-way-to-deploy-mysql in their system. But we should also pick some easy to use default for others that might need it.

**Comment by maugustosilva** [comment]
Fixed by #16, with at least two options (`sqlite` and `mysql`)
