### ISSUE TITLE
Include mechanism to deploy controller through bundle to be able to deploy controller through operator-sdk

### ISSUE THREAD

**Issue by sarroutbi** [keylime/attestation-operator#52]
Right now, deployment of attestation-controller is done through kustomize.

A mechanism to deploy the controller through operator-sdk should be included, as an alternative. `operator-sdk` based controllers are the ones used in Red Hat catalog so, if the operator can be deployed this way, it will ease the mechanism to include the controller in OpenShift catalog.

Of course, including this way of mechanism is an alternative, and current deployment mechanism should be maintained

**Comment by mheese** [comment]
It is not done that way. It's deployed through the helm chart

**Comment by mheese** [comment]
Sorry, didn't mean to close this issue
