### ISSUE TITLE
Enable Packit in the repository for CI setup

### ISSUE THREAD

**Issue by ansasaki** [keylime/attestation-operator#61]
Hello, I would like to enable Packit here, but I don't have the permission to change the configuration in this repo.

We are using Packit-as-a-Service in all other repos (https://github.com/keylime/keylime, https://github.com/keylime/rust-keylime, and https://github.com/RedHat-SP-Security/keylime-tests) for CI testing.

Could one of the maintainers please enable Packit-as-a-Service application here?
The instructions are provided in their documentation: https://packit.dev/docs/guide

The goal is to try to setup an alternative for the AWS CI using the same infrastructure we currently use for the other repos.

**Comment by maugustosilva** [comment]
Hello @ansasaki , I have checked, and you're one of the 5 members in `keylime/operator-core` . `Packit-as-a-Service` is already installed (and seemingly configured) on this repo. Please look for me at the CNCF Slack so we can further debug this.

**Comment by ansasaki** [comment]
Hi @maugustosilva,
It seems that being in the `/keylime/operator-core` group is not sufficient to have access to this repo's settings, as I cannot access it. I'll follow-up on slack about the access issue.

About enabling Packit here, I'll close this issue after confirming it is enabled. Thank you for checking!

**Comment by maugustosilva** [comment]
The `/keylime/operator-core` group did not have `admin` privileges itself. I have just fixed now, and I believe we are good to go. Will close the issue for now, feel free to re-open as needed.
