### ISSUE TITLE
panic during make bundle

### ISSUE THREAD

**Issue by ramrattle** [keylime/attestation-operator#78]
Hi all, I was trying to build operator plugin, once the image is built and pushed I tried below command but getting a error, can someone give some pointers pls

root@maste# make bundle DOCKER_TAG=[quay.io/ramrattle/attestation-operator:v0.1.0](http://quay.io/ramrattle/attestation-operator:v0.1.0)
/home/test/ram/attestation-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0b44f]

**Comment by sarroutbi** [comment]
Hello @ramrattle . This seems pretty similar to https://github.com/latchset/tang-operator/issues/248, which was also related to https://github.com/golang/go/issues/64812. Are you using Go v1.22 version?

In that case, it was fixed by upgrading to latest values of different packages so that controller-gen is updated. We might need this at this moment as well.

I'll have  a look at it to check if it is related.

**Comment by ramrattle** [comment]
Thanks a lot for your reply, let me check the Go version, meanwhile would be really helpful if you can help with one of my query, 

how to run agent container in worker node?  currently I have a master node and worker node connected with kubeadm, I want attester, verifier, tenant to run on master node and agent alone to run on worker node, how can I achieve this?? will be helpful if you can give any pointers alos.

**Comment by sarroutbi** [comment]
> Thanks a lot for your reply, let me check the Go version, meanwhile would be really helpful if you can help with one of my query,
> 
> how to run agent container in worker node? currently I have a master node and worker node connected with kubeadm, I want attester, verifier, tenant to run on master node and agent alone to run on worker node, how can I achieve this?? will be helpful if you can give any pointers alos.

Hello. May I ask you to query on slack Channel for that purpose, specifying the steps you follow, infrastructure being used, etc.etc.etc? Or, at least, you can open a new issue to avoid different matters being mixed and mingled?

**Comment by ramrattle** [comment]
for sure,  sorry for the mix-up
